.commitlintrc.cjs
.github/workflows/_docker.yaml
.github/workflows/_tests.yaml
.github/workflows/ci.yaml
.github/workflows/release.yaml
.husky/commit-msg
.husky/pre-commit
.releaserc.cjs
Dockerfile
bin/entrypoint.sh
config/default.json
config/development.json
package-lock.json
package.json
src/constants.ts
src/index.ts
src/lib/updater.ts

feat: self-update docker image

---

src/helper/api-connect-handler.ts
src/helper/api-error-handler.ts
src/index.ts
src/types.d.ts

related to https://github.com/jsdelivr/globalping/pull/49
Adds:
- `api:error` event - logs the reason for the disconnect
- `api:connect:location` - logs probe's geo fetch result
```
[2022-03-24 12:19:12] [ERROR] [766473] [general] disconnected due to error: IP Limit
[2022-03-24 12:19:12] [INFO] [766473] [general] attempted to connect from (boblingen, DE, EU) (lat: 48.6821 long: 9.0117)
[2022-03-24 12:19:12] [INFO] [766473] [general] other connection: (naarden, NL, EU) (lat: 52.29 long: 5.15)
```
```
[2022-03-24 12:19:12] [INFO] [766479] [general] connected from (naarden, NL, EU) (lat: 52.29 long: 5.15)
```

feat: support custom events

---

.github/workflows/_docker.yaml
.github/workflows/ci.yaml
.github/workflows/release.yaml

chore: add test for Docker file build

---

src/command/dns-command.ts

https://github.com/jsdelivr/globalping/issues/62

ref: dns: parse serer/resolver value

---

src/command/traceroute-command.ts

https://github.com/jsdelivr/globalping/issues/57

fix: traceroute/progress: trim removes linebreaks

---

package-lock.json
package.json
src/command/dns-command.ts
src/command/ping-command.ts
src/command/traceroute-command.ts
src/helper/execa-error-check.ts
test/mocks/dns-resolver-error-linux.json
test/mocks/dns-resolver-error-linux.txt
test/mocks/dns-success-linux.json
test/mocks/dns-success-linux.txt
test/unit/cmd/dns.test.ts

resolve #2
done:
- add: dig parser
- remove: node-dig-dns
- add: unit tests

wip: ref: use dig for DNS query

---

src/command/ping-command.ts

feat: force ipv4 on PING command

---

src/command/dns-command.ts
src/command/handlers/dig/classic.ts
src/command/handlers/dig/shared.ts
src/command/handlers/dig/trace.ts
test/mocks/dig/trace.success.txt
test/mocks/dns-trace-success.json
test/mocks/dns-trace-success.txt
test/unit/cmd/dns.test.ts
test/unit/cmd/helpers/dig/trace.test.ts

feat: add dig-trace support

---

src/index.ts

add: log disconnection reason + force reconnect on disconnect event

---

src/index.ts

resolve https://github.com/jsdelivr/globalping/issues/130

fix: prevent reconnect on VPN detection

---

package-lock.json
package.json
src/command/dns-command.ts
src/command/handlers/dig/shared.ts
src/command/ping-command.ts
src/command/traceroute-command.ts
test/mocks/dns-resolved-private-ip-error-linux.json
test/mocks/dns-resolved-private-ip-error-linux.txt
test/mocks/dns-trace-resolved-private-ip-error-linux.json
test/mocks/dns-trace-resolved-private-ip-error-linux.txt
test/mocks/ping-private-ip-linux.json
test/mocks/ping-private-ip-linux.txt
test/mocks/trace-private-ip-linux.json
test/mocks/trace-private-ip-linux.txt
test/unit/cmd/dns.test.ts
test/unit/cmd/ping.test.ts
test/unit/cmd/trace.test.ts

feat: prevent private targets

---

src/command/http-command.ts
test/unit/cmd/http.test.ts

fix: http improvements

---

Dockerfile
src/command/dns-command.ts
src/command/handlers/dig/trace.ts
src/command/ping-command.ts
src/command/traceroute-command.ts
test/mocks/dns-trace-success.json

resolve https://github.com/jsdelivr/globalping/issues/134
resolve https://github.com/jsdelivr/globalping/issues/104

disable pipe buffer on all cmds

---

src/command/mtr-command.ts
test/mocks/mtr-fail-private-ip.json
test/unit/cmd/mtr.test.ts

fix: private IP check on MTR

---

package-lock.json
package.json
src/command/mtr-command.ts

mentioned in https://github.com/jsdelivr/globalping/issues/127
The private IP check was attempting to query DNS, of an IP address.

fix: mtr fail on ip target

---

bin/entrypoint.sh
package.json
src/helper/api-connect-handler.ts
src/index.ts
src/lib/dependencies.ts
src/sh/unbuffer.sh

feat: unbuffer sideload + validate

---

package-lock.json
package.json
src/command/http-command.ts

fix: disable tls cert cache

---

src/command/dns-command.ts
src/command/http-command.ts
test/unit/cmd/dns.test.ts
test/unit/cmd/http.test.ts

relies on https://github.com/jsdelivr/globalping/pull/170

fix: update dns + http schema

---

config/default.json
config/development.json
src/command/dns-command.ts
src/command/mtr-command.ts
src/command/ping-command.ts
src/command/traceroute-command.ts
test/unit/cmd/dns.test.ts
test/unit/cmd/mtr.test.ts
test/unit/cmd/ping.test.ts
test/unit/cmd/trace.test.ts

ref: test options to arguments conversion

---

.mocharc.json
package-lock.json
package.json

Replaces scripts with tsx loaders to speed up tests and add additional dev scripts.

chore: use tsx loaders and scripts

---

README.md

Just wanted to add an extra note about the unbuffer package, since the automated script fails using WSL.

docs: add dev setup

---

src/command/dns-command.ts
src/command/handlers/dig/classic.ts

fix: broken private IP indicator + partial parse (empty rawOutput)

---

src/command/dns-command.ts

related to, but probably doesn't resolve #200

fix: dns: progress parse fail

---

src/command/dns-command.ts
src/command/handlers/mtr/types.ts
src/command/http-command.ts
src/command/mtr-command.ts
src/command/ping-command.ts
src/command/traceroute-command.ts
src/constants.ts
src/helper/progress-buffer-overwrite.ts
src/helper/progress-buffer.ts
test/unit/cmd/helper/progress-buffer-overwrite.test.ts
test/unit/cmd/helper/progress-buffer.test.ts
test/unit/cmd/http.test.ts
test/unit/cmd/mtr.test.ts

Fixes https://github.com/jsdelivr/globalping/issues/225
500ms window seems a best balance between "real-life" behavior and ability to batch something together.

Buffer progress messages

---

src/lib/updater.ts
test/unit/lib/updater.test.ts

Fixes https://github.com/jsdelivr/globalping/issues/288

fix: ignore gh server timeout errors

---

src/command/dns-command.ts
src/command/http-command.ts
src/command/mtr-command.ts
src/command/ping-command.ts
src/command/traceroute-command.ts
src/index.ts
src/lib/logger.ts

Part of https://github.com/jsdelivr/globalping/issues/212
Added:
- logging of non-expected errors (stack and metadata)
- logging measurement metadata in case of empty stdout

feat: add logging of errors or unexpected behavior

---

package.json
src/command/handlers/dig/classic.ts
src/command/handlers/dig/shared.ts
src/command/handlers/dig/trace.ts
src/command/handlers/mtr/parser.ts
src/command/handlers/ping/parse.ts
src/command/ping-command.ts
src/constants.ts
src/helper/api-connect-handler.ts
src/index.ts
src/lib/status-manager.ts
src/types.d.ts
test/mocks/ping-packet-loss-linux.txt
test/unit/command/handlers/http/dns-resolver.test.ts
test/unit/command/http-command.test.ts
test/unit/index.test.ts
test/unit/lib/dependencies.test.ts
test/unit/lib/status-manager.test.ts
test/unit/lib/updater.test.ts

feat: probe status manager

---

package-lock.json
package.json
src/index.ts
src/types.d.ts
test/unit/index.test.ts

Part of https://github.com/jsdelivr/globalping/issues/310

feat: get test id from the API

---

config/default.json
src/lib/status-manager.ts
test/unit/lib/status-manager.test.ts

Fixes https://github.com/jsdelivr/globalping/issues/315

feat: lower qa requirements

---

config/default.json
src/command/dns-command.ts
src/command/http-command.ts
src/command/mtr-command.ts
src/command/ping-command.ts
src/command/traceroute-command.ts
src/lib/status-manager.ts
src/types.d.ts
test/unit/command/dns-command.test.ts
test/unit/command/http-command.test.ts
test/unit/command/mtr-command.test.ts
test/unit/command/ping-command.test.ts
test/unit/command/traceroute-command.test.ts
test/unit/lib/status-manager.test.ts

Fixes https://github.com/jsdelivr/globalping/issues/308

feat: reduce the number of progress messages

---

src/command/http-command.ts
src/helper/progress-buffer.ts
test/unit/command/http-command.test.ts
test/unit/helper/progress-buffer.test.ts

Fixes https://github.com/jsdelivr/globalping-probe/issues/137

feat: send rawHeader and rawBody during http progress messages

---

src/lib/status-manager.ts

fixes https://github.com/jsdelivr/globalping-probe/issues/134

refactor: update status manager logging

---

src/command/http-command.ts
test/unit/command/http-command.test.ts

Fixes https://github.com/jsdelivr/globalping/issues/355

feat: remove http2 pseudo-headers from rawHeaders

---

src/command/http-command.ts
test/unit/command/http-command.test.ts

Fixes https://github.com/jsdelivr/globalping-probe/issues/130

fix: fix http measurements with invalid port

---

src/lib/status-manager.ts
test/unit/lib/status-manager.test.ts

https://github.com/jsdelivr/globalping-hwprobe/issues/21

feat: change root server

---

src/helper/api-error-handler.ts
src/index.ts
src/types.d.ts
test/unit/index.test.ts

Fixes https://github.com/jsdelivr/globalping/issues/367

fix: ip limit log abuse

---

src/lib/status-manager.ts
test/unit/lib/status-manager.test.ts

https://github.com/jsdelivr/globalping-probe/issues/135

feat: different qa endpoints

---

src/command/dns-command.ts
src/command/ping-command.ts
src/command/traceroute-command.ts
src/helper/api-connect-handler.ts
src/helper/api-error-handler.ts
src/index.ts
src/lib/logger.ts
src/lib/restart.ts
src/lib/stats/client.ts
src/lib/status-manager.ts
src/lib/updater.ts
src/types.d.ts

Fixes https://github.com/jsdelivr/globalping-probe/issues/152

feat: update log messages

---

src/helper/api-error-handler.ts
src/index.ts
src/types.d.ts
test/unit/index.test.ts

Fixes https://github.com/jsdelivr/globalping/issues/390
Should be released after https://github.com/jsdelivr/globalping/pull/395

feat: refactor error message api-probe communication

---

src/command/dns-command.ts
src/command/handlers/dig/classic.ts
src/command/handlers/http/dns-resolver.ts
src/command/mtr-command.ts
src/command/ping-command.ts
src/command/traceroute-command.ts
src/lib/dns.ts
src/lib/private-ip.ts

Same as https://github.com/jsdelivr/globalping/pull/410

refactor: replace `private-ip` with Node.js native API

---

src/constants.ts
src/index.ts
src/lib/log-adoption-code.ts

Part of https://github.com/jsdelivr/globalping/issues/425

feat: adoption probes

---

src/lib/private-ip.ts

fix: correctly parse AAAA records (#190)

---

src/index.ts
test/unit/index.test.ts

Part of https://github.com/jsdelivr/globalping-probe/issues/193

feat: send new admin vars to the api

---

src/command/dns-command.ts
test/snapshots/command/dns-command.test.json
test/unit/command/dns-command.test.ts

Part of https://github.com/jsdelivr/globalping/issues/468

feat: add HTTPS DNS type support

---

test/snapshots/command/dns-command.test.json
test/unit/command/dns-command.test.ts

Part of https://github.com/jsdelivr/globalping/issues/503

feat: allow DNS requests for TLDs and root zone

---

src/command/handlers/ping/parse.ts
test/mocks/ping-no-source-ip-linux.json
test/mocks/ping-no-source-ip-linux.txt
test/unit/command/ping-command.test.ts

Fixes https://github.com/jsdelivr/globalping-probe/issues/213

fix: ping parse line without source ip

---

bin/entrypoint.sh

feat: add a way to force update to a specific version

---

src/index.ts

Instead of `node_modules`, which get deleted during updates.

fix: install new node versions to /nvm

---

bin/entrypoint.sh

feat: allow post-update patching

---

src/index.ts
src/lib/util.ts
src/probe.ts
test/unit/lib/util.test.ts

refactor: lower the memory requirements for node updates

---

config/default.cjs

fix: switch from ws to wss for API communication

---

src/command/handlers/ping/parse.ts
test/mocks/ipv6-ping-success-no-domain.json
test/mocks/ipv6-ping-success-no-domain.txt
test/mocks/ping-success-linux-no-domain.json
test/mocks/ping-success-linux-no-domain.txt
test/unit/command/ping-command.test.ts

fix: improve ping output parsing for IP targets

---

src/helper/adoption-status-handler.ts
src/helper/alt-ips-handler.ts
src/probe.ts

Fixes https://github.com/jsdelivr/globalping-probe/issues/251

feat: add dashboard link log message

---

.github/workflows/_tests.yaml
config/e2e-api-test.cjs
package.json

test: fix e2e tests

---

config/default.cjs
src/command/dns-command.ts
src/command/handlers/ping/parse.ts
src/command/http-command.ts
src/command/mtr-command.ts
src/command/ping-command.ts
src/command/traceroute-command.ts
test/mocks/dns-resolved-private-ip-invalid-hostname-linux.json
test/mocks/dns-trace-resolved-private-ip-invalid-hostname-linux.json
test/mocks/ipv6-dns-resolved-private-ip-invalid-hostname-linux.json
test/mocks/ipv6-dns-trace-resolved-private-ip-invalid-hostname-linux.json
test/mocks/mtr-fail-private-ip.json
test/mocks/ping-private-ip-linux.json
test/mocks/trace-private-ip-linux.json
test/unit/command/dns-command.test.ts
test/unit/command/mtr-command.test.ts
test/unit/command/ping-command.test.ts
test/unit/command/traceroute-command.test.ts

Fixes https://github.com/jsdelivr/globalping-probe/issues/275

feat: execa-level timeouts

---

.github/workflows/_docker.yaml
config/default.cjs
src/command/dns-command.ts
src/command/handlers/dig/classic.ts
src/command/handlers/dig/shared.ts
src/command/handlers/dig/trace.ts
src/command/handlers/ping/parse.ts
src/command/http-command.ts
src/command/mtr-command.ts
src/command/ping-command.ts
src/command/traceroute-command.ts
src/lib/stats/cpu.ts
test/mocks/dns-resolved-private-ip-invalid-hostname-linux.json
test/mocks/dns-trace-resolved-private-ip-invalid-hostname-linux.json
test/mocks/ipv6-dns-resolved-private-ip-invalid-hostname-linux.json
test/mocks/ipv6-dns-trace-resolved-private-ip-invalid-hostname-linux.json
test/mocks/mtr-fail-private-ip.json
test/mocks/ping-private-ip-linux.json
test/mocks/trace-private-ip-linux.json
test/unit/command/dns-command.test.ts
test/unit/command/mtr-command.test.ts
test/unit/command/ping-command.test.ts
test/unit/command/traceroute-command.test.ts

Part of https://github.com/jsdelivr/meta/issues/52

fix: replace possible undefineds with nulls

---

src/index.ts

fix: improve the persistent UUID error message

---

src/command/http-command.ts
test/unit/command/http-command.test.ts

Related to https://github.com/jsdelivr/www.jsdelivr.com/issues/729

feat: add TLS version and cipher to HTTP tests

---

src/lib/fake-ip.ts
src/probe.ts

Part of https://github.com/jsdelivr/globalping-dash-directus/issues/58

feat: pass first 3 octets of fake ip

---

src/lib/stats/cpu.ts

Fixes https://github.com/jsdelivr/globalping-probe/issues/285

fix: null value in cpu usage
