jsdelivr/globalping-probe

- @types/node-dig-dns.d.ts
- package-lock.json
- package.json
- src/command/dns-command.ts
- src/index.ts
- tsconfig.json
resolve #2
There's not many actively maintained libraries around, since node's official package resolves DNS pretty well (https://nodejs.org/api/dns.html).
It doesn't however seem to support protocol selection, so that won't work for us.
My initial commit implemented [domain-info](https://www.npmjs.com/package/domain-info) package, but I decided to ditch it since it doesn't seem to be actively maintained either, its last build failed. It supports multi dns type queries, which is interesting. The package @zarianec ([node-dig-dns](https://www.npmjs.com/package/node-dig-dns)) has proposed on the other hand, doesn't include types so they had to be included manually.
No tests, since theres nothing to test. Parsing is handled by the library.
> Add: support dns (lookup) command

- Dockerfile
I know we dont support them yet but since we assume users will rarely pull new Docker containers we will run into an issue where once we add support for them none of existing probes will be able to run them because there wont be a binary present.
So we should add all the binaries we might need right now. This way even the oldest probes will have them and will work fine after the code auto-update.
Am I missing any other packages?
> fix: add new packages to Dockerfile

- @types/node-dig-dns.d.ts
- src/command/dns-command.ts
- src/command/ping-command.ts
- src/command/traceroute-command.ts
ping + traceroute:
captures the error, and returns `stderr` in `rawOutput` field.
dns:
returns an object with the following values:
`answer` - [array] array of results
`time` - [number] Query time.
`server` - [string] resolver. Plain response from the dig command.
https://github.com/jsdelivr/globalping/issues/61
https://github.com/jsdelivr/globalping/issues/62
> ref: measurement results behaviour

- bin/entrypoint.sh
Since we assume the container will never get updated it will break HTTPS sooner or later due to expired certs. So my idea is to run `update-ca-certificates` to update them before downloading an agent update.
> improvement: update-ca-certificates

- config/default.json
- src/index.ts
- src/lib/restart.ts
#38
Sends `SIGTERM` signal every 12 hrs. 
It doesn't rely on #31, but it would be better to merge it first.
> feat: health restart every ~7 days

- src/index.ts
- src/lib/config.ts
- src/lib/logger.ts
- src/lib/updater.ts
resolve #17
- dont accept new connections, until `connect` event is received
- on `connect` emit `probe:status:ready` event
- on `SIGTERM` emit `probe:status:not_ready` event
- on `SIGTERM` block new measurement requests
- send `SIGTERM` on update completion
- on `SIGTERM`, don't close the app until all jobs are completed
> feat: capture SIGTERM, close after job completion

- src/index.ts
initial problem:
probes don't reconnect after server initiated `disconnect`
current problem:
probes don't reconnect after their first `connect` failure.
reasoning:
the client doesn't attempt to reconnect on an explicit `disconnect` request. However, forcing a `connect` attempt while the client's `reconnect` handler is enabled, causes the `reconnect` handler to quit. We have to isolate the reason of the disconnect and only manually reconnect if the reconnect handler isn't running.
> fix: connect stops reconnect handler

- src/index.ts
Repeated `socket.connect()` prevents the client from reconnecting.
> fix: disconnect on fatal connection error

- src/command/dns-command.ts
- src/command/ping-command.ts
- src/command/traceroute-command.ts
Just for good measure. Normally this shouldn't be an issue, and I'm unable to replicate it under any circumstances, since the `probe:measurement:result` event kicks in immidatelly.
related to https://github.com/jsdelivr/globalping/issues/134
> fix: private IP - prevent progress update

- src/command/dns-command.ts
- src/command/handlers/dig/classic.ts
- src/command/handlers/dig/shared.ts
- src/command/handlers/dig/trace.ts
- src/command/handlers/mtr/parser.ts
- src/command/handlers/mtr/types.ts
- src/command/http-command.ts
- src/command/mtr-command.ts
- src/command/ping-command.ts
- src/command/traceroute-command.ts
- test/mocks/dns-success-linux.json
- test/mocks/dns-trace-success.json
- test/mocks/mtr-fail-private-ip.json
- test/mocks/mtr-success-raw-helper-final.json
- test/mocks/mtr-success-raw-helper-progress.json
- test/mocks/mtr-success-raw.json
- test/mocks/ping-success-linux.json
- test/mocks/ping-success-linux.txt
- test/mocks/ping-success-mac.json
- test/mocks/ping-success-mac.txt
- test/mocks/ping-timeout-linux.json
- test/mocks/ping-timeout-mac.json
- test/mocks/trace-success-linux.json
- test/unit/cmd/helpers/dig/trace.test.ts
- test/unit/cmd/http.test.ts
resolve https://github.com/jsdelivr/globalping/issues/157
1. ping
2. traceroute
3. dns
4. mtr
5. http
> ref: response schemas

- src/command/http-command.ts
- test/unit/cmd/http.test.ts
Resolves #79. Adds one test case. I don't think there is anything to do for http/2 since they [removed the relevant headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive) from the spec, right?
> fix: enforce keepAlive headers to be false

- src/command/ping-command.ts
- test/unit/cmd/ping.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/213
We can add error parsing to other commands, but currently I didn't found use cases with the same behavior. Behavior:
- command exits with non 0 exit code;
- command output has data that can be included in the result and it is not included currently.
> feat: parsing of ping execa errors

- src/command/dns-command.ts
- src/command/handlers/dig/classic.ts
- src/command/handlers/dig/trace.ts
- src/command/handlers/mtr/types.ts
- src/command/http-command.ts
- src/command/mtr-command.ts
- src/command/ping-command.ts
- src/command/traceroute-command.ts
- test/mocks/dns-connection-refused-error-linux.json
- test/mocks/dns-connection-refused-private-error-linux.json
- test/mocks/dns-resolved-private-ip-error-linux.json
- test/mocks/dns-resolver-error-linux.json
- test/mocks/dns-success-linux.json
- test/mocks/dns-trace-resolved-private-ip-error-linux.json
- test/mocks/dns-trace-success.json
- test/mocks/mtr-fail-private-ip.json
- test/mocks/mtr-success-raw.json
- test/mocks/ping-private-ip-linux.json
- test/mocks/ping-success-linux.json
- test/mocks/ping-success-mac.json
- test/mocks/ping-timeout-linux.json
- test/mocks/ping-timeout-mac.json
- test/mocks/trace-private-ip-linux.json
- test/mocks/trace-success-linux.json
- test/unit/command/dns-command.test.ts
- test/unit/command/http-command.test.ts
- test/unit/command/ping-command.test.ts
- test/unit/index.test.ts
Adds status field to the result field of the measurement. Possible values are: `in-progress`, `finished`, and `failed`.
Part of https://github.com/jsdelivr/globalping/issues/212
> feat: measurement statuses

- .github/workflows/release.yaml
This PR adds an additional step in the "Release" CI job to mark the working directory as a git safe.
This will fix the error below that prevents the `semantic-release` from creating a new release.
```
Error message: detected dubious ownership in repository
```
> ci: mark working directory safe

- src/helper/api-connect-handler.ts
- src/index.ts
- test/unit/index.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/296
Should be deployed in parallel with https://github.com/jsdelivr/globalping/pull/297 . In that order:
1. Release https://github.com/jsdelivr/globalping-probe/pull/116 and pick by the probes
2. Deploy https://github.com/jsdelivr/globalping/pull/297
> feat: probe status from boolean to string

- src/lib/status-manager.ts
- test/unit/lib/status-manager.test.ts
Socket.IO provides an at most once guarantee of delivery. That means we can't cache and rely on the local status of the probe, as API may loose the message and status there will be different. That is why we should send probe status on every check. Since that happens once in 10 mins and the payload is a few words that will not add any additional load to the system.
https://socket.io/docs/v4/delivery-guarantees#at-most-once
> fix: fix probes stuck in the INITIALIZING status

- src/command/dns-command.ts
- src/lib/types.ts
- test/unit/command/dns-command.test.ts
Fixes: https://github.com/jsdelivr/globalping-probe/issues/139
Broken version of command:
`dig 172.67.208.113 @1.1.1.1 -x -p 53 -4 +timeout=3 +tries=2 +nocookie`
Fixed:
`dig -x 172.67.208.113 @1.1.1.1 -p 53 -4 +timeout=3 +tries=2 +nocookie `
All other dns types and args combinations work fine before and after the fix.
> fix: fix ptr dns type

- src/command/dns-command.ts
- test/unit/command/dns-command.test.ts
Fixes https://github.com/jsdelivr/globalping-probe/issues/149
Example of the response:
```
; <<>> DiG 9.16.37-Debian <<>> -t A jsdelivr.com @1.1.1.1 -p 53 -4 +timeout=3 +tries=2 +nocookie +nsid
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3432
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; NSID: 38 37 6d 33 36 32 ("87m362")
;; QUESTION SECTION:
;jsdelivr.com.			IN	A
;; ANSWER SECTION:
jsdelivr.com.		300	IN	A	104.21.23.24
jsdelivr.com.		300	IN	A	172.67.208.113
;; Query time: 34 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Thu May 25 09:17:09 UTC 2023
;; MSG SIZE  rcvd: 83
```
> feat: add +nsid to dns commands

- .gitignore
- src/command/http-command.ts
- test/unit/command/http-command.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/386
> fix: fix http timings total and download fields

- src/helper/api-error-handler.ts
- test/unit/index.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/417
- Updates to reconnect after 'ip limit' error in 1 hour.
- Updates to reconnect after 'failed to collect probe metadata' error in 1 min. (This is a consequence of the `fetchSockets timeout` on the API side, so reconnect should be done faster).
> feat: separate probe and api errors

- src/index.ts
- test/unit/index.test.ts
Fixes https://github.com/jsdelivr/globalping-probe/issues/179
> feat: update socket.io reconnect delay

- .github/workflows/ci.yaml
- src/command/http-command.ts
- test/unit/command/http-command.test.ts
Fixes https://github.com/jsdelivr/globalping/issues/357
> feat: add truncated true|false for HTTP tests

- Dockerfile
Lower 10.x.x versions have a bug that overloads the network and causes install failures: https://github.com/npm/cli/issues/7072
> build: use npm v10.5.2

- src/command/handlers/ping/parse.ts
- test/mocks/ping-unreachable-linux.json
- test/mocks/ping-unreachable-linux.txt
- test/unit/command/ping-command.test.ts
> fix: improve ping totals parsing in case of errors

- src/helper/alt-ips-handler.ts
- test/unit/helper/alt-ips-handler.test.ts
- don't try private IPs
- set a timeout; misconfigured IPs often cause the request to hang
- log failures as warnings instead of errors
> fix: improve handling of alternative IPs

- src/lib/logger.ts
- src/lib/updater.ts
- test/unit/lib/updater.test.ts
A bit ugly but makes all got errors much shorter while keeping the important parts. Related: jsdelivr/globalping#550
> fix: reduce the size of log messages for update errors

- Dockerfile
The Dockerfile had a couple of errors causing leftover in the resulting image.
This PR reduces the resulting image by around 80MB:
> build: cleanup docker image leftovers

- src/command/http-command.ts
- test/unit/command/http-command.test.ts
- wallaby.js
Part of https://github.com/jsdelivr/globalping-probe/issues/261
> feat: add OPTIONS as an allowed HTTP Method

- src/lib/api-logs-transport.ts
- src/lib/logger.ts
- test/unit/lib/api-logs-transport.test.ts
> fix: handle objects and long messages in API log transport
